CREATE VIEW [dbo].[VW_CHURN_PAGAMENTOS] AS
SELECT 
	PD.ORDER_ID AS ID_PEDIDO,
	PD.ORDER_STATUS AS STATUS_PEDIDO,
	PD.ORDER_PURCHASE_TIMESTAMP AS DATA_COMPRA,
	PG.PAYMENT_TYPE AS TIPO_PAGAMENTO,
	SUM(PG.PAYMENT_VALUE) AS VALOR_PAGO,
	CL.CUSTOMER_STATE AS ESTADO,
	CL.CUSTOMER_CITY AS CIDADE

FROM PEDIDOS PD
	INNER JOIN PAGAMENTOS PG ON PG.ORDER_ID = PD.ORDER_ID
	INNER JOIN CLIENTES CL ON CL.CUSTOMER_ID = PD.CUSTOMER_ID

GROUP BY
	PD.ORDER_ID,
	PD.ORDER_STATUS,
	PD.ORDER_PURCHASE_TIMESTAMP, 
	PG.PAYMENT_TYPE,
	CL.CUSTOMER_STATE,
	CL.CUSTOMER_CITY


